spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "1.0"

accounts:
  message: "Welcome to EasyBank accounts related QA APIs "
  contactDetails:
    name: "Samira Radmaneshfar - Software Engineer"
    email: "Samira.Radmaneshfar@gamil.com"
